use std::fs;
use std::path::Path;

use super::router::{QueryIntent, RouterDecision};
use super::skills::AgentSkill;
use super::types::{AgentConversationMessage, AgentReference, AgentSkillMode};
use super::workspace::agent_workspace_display;

const MAX_OVERVIEW_CHARS: usize = 8_000;
const MAX_SCHEMA_CHARS: usize = 6_000;
const MAX_HISTORY_CHARS: usize = 12_000;
const MAX_REFERENCE_CHARS: usize = 24_000;
const MAX_SKILL_CHARS: usize = 18_000;
const MAX_AUTO_SKILL_INDEX_CHARS: usize = 12_000;
const MAX_AUTO_SKILLS: usize = 48;

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectContext {
    pub overview: Option<String>,
    pub schema: Option<String>,
    pub agent_workspace: String,
}

pub fn load_project_context(project_path: &str) -> ProjectContext {
    let root = Path::new(project_path);
    ProjectContext {
        overview: read_trimmed(root.join("overview.md"), MAX_OVERVIEW_CHARS)
            .or_else(|| read_trimmed(root.join("wiki").join("overview.md"), MAX_OVERVIEW_CHARS)),
        schema: read_trimmed(root.join("schema.md"), MAX_SCHEMA_CHARS)
            .or_else(|| read_trimmed(root.join("wiki").join("schema.md"), MAX_SCHEMA_CHARS)),
        agent_workspace: agent_workspace_display(root),
    }
}

#[derive(Debug, Clone)]
pub struct AgentContextInput<'a> {
    pub query: &'a str,
    pub project: &'a ProjectContext,
    pub router: &'a RouterDecision,
    pub history: &'a [AgentConversationMessage],
    pub skills: &'a [AgentSkill],
    pub skill_mode: AgentSkillMode,
    pub references: &'a [AgentReference],
    pub retrieval_summary: &'a str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BuiltAgentContext {
    pub system: String,
    pub user: String,
}

pub fn build_agent_context(input: AgentContextInput<'_>) -> BuiltAgentContext {
    BuiltAgentContext {
        system: build_system_context(input.project, input.router, input.skills, input.skill_mode),
        user: build_user_context(input),
    }
}

fn build_system_context(
    project: &ProjectContext,
    router: &RouterDecision,
    skills: &[AgentSkill],
    skill_mode: AgentSkillMode,
) -> String {
    let mut out = [
        "You are the LLM Wiki backend Agent.",
        "Answer using the current project context, available tools, and cited references.",
        "If evidence is insufficient, say what is missing instead of inventing facts.",
        "When using references, mention the relevant page paths naturally.",
        "Do not claim that internet or local-source search is unavailable when those tools are enabled; use the provided tool context and tool hints.",
    ]
    .join("\n");

    out.push_str("\n\nTool policy:\n");
    out.push_str("- wiki.search can search generated wiki pages.\n");
    if router.should_hint_web {
        out.push_str("- web.search is available when current or external information is useful.\n");
    }
    if router.should_hint_anytxt {
        out.push_str(
            "- anytxt.search is available for local or remote file content indexed by AnyTXT.\n",
        );
    }
    out.push_str(&format!(
        "- Router hint: {:?}. {}\n",
        router.intent, router.rationale
    ));
    out.push_str("\nGenerated file policy:\n");
    out.push_str(&format!(
        "- All files generated by the Agent, skills, shell commands, scripts, image tools, HTML exports, or any future generation feature must be created under this visible project workspace: {}.\n",
        project.agent_workspace
    ));
    out.push_str("- Do not create generated files in the user's home folder, Desktop, Downloads, system temp folders, hidden app metadata folders, or skill installation folders.\n");
    out.push_str("- Treat skill folders as read-only instruction/reference sources. If a skill or script needs output files, pass or choose a path under the Agent workspace above.\n");
    out.push_str("- If the requested visual can be represented as a Mermaid diagram, reply with a ```mermaid fenced code block directly instead of generating an HTML file just to display that diagram.\n");
    out.push_str("- When using shell.exec, prefer relative output paths because the shell runs from the Agent workspace; use the LLM_WIKI_AGENT_WORKSPACE environment variable when an absolute output path is required.\n");

    if let Some(overview) = project.overview.as_deref().filter(|v| !v.trim().is_empty()) {
        out.push_str("\n\nProject overview:\n");
        out.push_str(&trim_chars(overview, MAX_OVERVIEW_CHARS));
    }
    if let Some(schema) = project.schema.as_deref().filter(|v| !v.trim().is_empty()) {
        out.push_str("\n\nProject schema:\n");
        out.push_str(&trim_chars(schema, MAX_SCHEMA_CHARS));
    }
    if !skills.is_empty() {
        match skill_mode {
            AgentSkillMode::Auto => {
                out.push_str("\n\nThe following skills provide specialized instructions for specific tasks.\n");
                out.push_str("Use a skill only when the latest request matches its description. To inspect a skill, use the listed SKILL.md location; when a skill references a relative path, resolve it against the skill directory.\n");
                out.push_str(&render_available_skills(skills));
            }
            AgentSkillMode::Explicit => {
                out.push_str("\n\nSelected skills:\n");
                out.push_str("The user explicitly selected the following skill instructions for this turn. Treat them as task-specific instructions and apply them unless they conflict with safety, project boundaries, or the user's latest request. Supporting files should still be read lazily from the listed skill directory only when needed.\n");
                let mut remaining = MAX_SKILL_CHARS;
                for skill in skills {
                    if remaining == 0 {
                        break;
                    }
                    let rendered = render_explicit_skill(skill);
                    let piece = trim_chars(&rendered, remaining);
                    remaining = remaining.saturating_sub(piece.chars().count());
                    out.push_str(&piece);
                    out.push('\n');
                }
            }
        }
    }
    out
}

fn render_available_skills(skills: &[AgentSkill]) -> String {
    let mut out = String::from("\n<available_skills>\n");
    let mut rendered = 0usize;
    for skill in skills.iter().take(MAX_AUTO_SKILLS) {
        let entry = format!(
            "  <skill>\n    <name>{}</name>\n    <description>{}</description>\n    <location>{}</location>\n  </skill>\n",
            escape_xml(&skill.name),
            escape_xml(skill.description.trim()),
            escape_xml(&skill.location)
        );
        let next_len = out.chars().count() + entry.chars().count();
        if next_len > MAX_AUTO_SKILL_INDEX_CHARS {
            break;
        }
        out.push_str(&entry);
        rendered += 1;
    }
    if rendered < skills.len() {
        out.push_str(&format!(
            "  <omitted>{} additional skill(s) omitted from the automatic index. Explicitly select a skill to include its full instructions.</omitted>\n",
            skills.len().saturating_sub(rendered)
        ));
    }
    out.push_str("</available_skills>\n");
    out
}

fn render_explicit_skill(skill: &AgentSkill) -> String {
    format!(
        "\n<skill name=\"{}\" location=\"{}\">\nReferences are relative to {}.\n\n{}\n</skill>",
        escape_xml(&skill.name),
        escape_xml(&skill.location),
        skill.base_dir,
        skill.instructions.trim()
    )
}

fn build_user_context(input: AgentContextInput<'_>) -> String {
    let mut out = String::new();
    if !input.history.is_empty() {
        out.push_str("Recent conversation history:\n");
        let mut history = String::new();
        for item in input.history.iter().rev().take(12).rev() {
            history.push_str(&format!(
                "{}: {}\n",
                item.role,
                collapse_whitespace(&item.content)
            ));
        }
        out.push_str(&trim_chars(&history, MAX_HISTORY_CHARS));
        out.push_str("\n\n");
    }

    out.push_str("Retrieved project context:\n");
    if input.references.is_empty() {
        out.push_str("No matching wiki references were found.\n\n");
    } else {
        let mut rendered = String::new();
        for (idx, reference) in input.references.iter().enumerate() {
            rendered.push_str(&format!(
                "{}. [{}] {} ({})\n",
                idx + 1,
                reference.kind,
                reference.title,
                reference.path
            ));
            if let Some(snippet) = reference.snippet.as_deref() {
                rendered.push_str(&format!("Snippet: {}\n", collapse_whitespace(snippet)));
            }
        }
        out.push_str(&trim_chars(&rendered, MAX_REFERENCE_CHARS));
        out.push('\n');
    }

    out.push_str("Retrieval summary:\n");
    out.push_str(&trim_chars(input.retrieval_summary, 8_000));
    out.push_str("\n\nLatest user request:\n");
    out.push_str(input.query.trim());
    out
}

fn read_trimmed(path: impl AsRef<Path>, max_chars: usize) -> Option<String> {
    let raw = fs::read_to_string(path).ok()?;
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trim_chars(trimmed, max_chars))
    }
}

pub fn trim_chars(value: &str, max_chars: usize) -> String {
    if value.chars().count() <= max_chars {
        return value.to_string();
    }
    let mut out = value
        .chars()
        .take(max_chars.saturating_sub(3))
        .collect::<String>();
    out.push_str("...");
    out
}

pub fn collapse_whitespace(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn escape_xml(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

pub fn intent_label(intent: QueryIntent) -> &'static str {
    match intent {
        QueryIntent::NeedsInternalSearch => "internal_search",
        QueryIntent::NeedsExternalSearch => "external_search",
        QueryIntent::NeedsRawSourceSearch => "raw_source_search",
        QueryIntent::NeedsGraph => "graph",
        QueryIntent::NeedsWrite => "write",
        QueryIntent::SimpleConversational => "conversation",
        QueryIntent::Ambiguous => "ambiguous",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::router::route_query;
    use crate::agent::types::{AgentMode, AgentToolOptions};

    #[test]
    fn context_keeps_stable_project_context_before_latest_request() {
        let project = ProjectContext {
            overview: Some("Project overview text".to_string()),
            schema: Some("Schema text".to_string()),
            agent_workspace: "/tmp/project/agent-workspace".to_string(),
        };
        let router = route_query(
            "latest policy",
            AgentMode::Standard,
            &AgentToolOptions::default(),
        );
        let ctx = build_agent_context(AgentContextInput {
            query: "latest policy",
            project: &project,
            router: &router,
            history: &[],
            skills: &[],
            skill_mode: AgentSkillMode::Auto,
            references: &[],
            retrieval_summary: "None",
        });

        assert!(ctx.system.contains("Project overview text"));
        assert!(ctx.system.contains("Schema text"));
        assert!(ctx.system.contains("Generated file policy"));
        assert!(ctx.system.contains("/tmp/project/agent-workspace"));
        assert!(ctx.user.ends_with("latest policy"));
    }

    #[test]
    fn context_distinguishes_auto_and_explicit_skill_modes() {
        let project = ProjectContext {
            overview: None,
            schema: None,
            agent_workspace: "/tmp/project/agent-workspace".to_string(),
        };
        let router = route_query(
            "draw an article image",
            AgentMode::Standard,
            &AgentToolOptions::default(),
        );
        let skills = vec![AgentSkill {
            name: "article-illustrator".to_string(),
            description: "Create article images".to_string(),
            instructions: "Use the local illustration helper when needed.".to_string(),
            base_dir: "/tmp/project/.llm-wiki/skills/article-illustrator".to_string(),
            location: "/tmp/project/.llm-wiki/skills/article-illustrator/SKILL.md".to_string(),
        }];

        let auto = build_agent_context(AgentContextInput {
            query: "draw an article image",
            project: &project,
            router: &router,
            history: &[],
            skills: &skills,
            skill_mode: AgentSkillMode::Auto,
            references: &[],
            retrieval_summary: "None",
        });
        let explicit = build_agent_context(AgentContextInput {
            query: "draw an article image",
            project: &project,
            router: &router,
            history: &[],
            skills: &skills,
            skill_mode: AgentSkillMode::Explicit,
            references: &[],
            retrieval_summary: "None",
        });

        assert!(auto.system.contains("<available_skills>"));
        assert!(auto.system.contains("<name>article-illustrator</name>"));
        assert!(auto.system.contains(
            "<location>/tmp/project/.llm-wiki/skills/article-illustrator/SKILL.md</location>"
        ));
        assert!(!auto.system.contains("Use the local illustration helper"));
        assert!(explicit.system.contains("Selected skills"));
        assert!(explicit.system.contains("explicitly selected"));
        assert!(explicit.system.contains("article-illustrator"));
        assert!(explicit
            .system
            .contains("location=\"/tmp/project/.llm-wiki/skills/article-illustrator/SKILL.md\""));
        assert!(explicit
            .system
            .contains("Use the local illustration helper"));
    }

    #[test]
    fn auto_skill_index_is_bounded() {
        let skills = (0..200)
            .map(|idx| AgentSkill {
                name: format!("skill-{idx}"),
                description: "x".repeat(500),
                instructions: "private instructions".to_string(),
                base_dir: format!("/tmp/skills/skill-{idx}"),
                location: format!("/tmp/skills/skill-{idx}/SKILL.md"),
            })
            .collect::<Vec<_>>();

        let rendered = render_available_skills(&skills);

        assert!(rendered.chars().count() <= MAX_AUTO_SKILL_INDEX_CHARS + 256);
        assert!(rendered.contains("<omitted>"));
        assert!(!rendered.contains("private instructions"));
    }

    #[test]
    fn explicit_skill_budget_counts_multibyte_chars_not_bytes() {
        let project = ProjectContext {
            overview: None,
            schema: None,
            agent_workspace: "/tmp/project/agent-workspace".to_string(),
        };
        let router = route_query(
            "使用这些技能",
            AgentMode::Standard,
            &AgentToolOptions::default(),
        );
        let skills = (0..4)
            .map(|idx| AgentSkill {
                name: format!("skill-{idx}"),
                description: format!("技能 {idx}"),
                instructions: format!("marker-{idx}\n{}", "界".repeat(3_000)),
                base_dir: format!("/tmp/skills/skill-{idx}"),
                location: format!("/tmp/skills/skill-{idx}/SKILL.md"),
            })
            .collect::<Vec<_>>();

        let explicit = build_agent_context(AgentContextInput {
            query: "使用这些技能",
            project: &project,
            router: &router,
            history: &[],
            skills: &skills,
            skill_mode: AgentSkillMode::Explicit,
            references: &[],
            retrieval_summary: "None",
        });

        assert!(explicit.system.contains("marker-0"));
        assert!(explicit.system.contains("marker-1"));
        assert!(explicit.system.contains("marker-2"));
        assert!(explicit.system.contains("marker-3"));
    }

    #[test]
    fn trim_chars_is_utf8_safe() {
        assert_eq!(trim_chars("煤矿安全治理", 5), "煤矿...");
    }
}
